# Generated by Django 5.2.8 on 2025-12-23 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('resit_start_date', models.DateTimeField(blank=True, null=True)),
                ('resit_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_period', to='portal.semester')),
            ],
            options={
                'db_table': 'enrollment_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResitExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('original_grade', models.CharField(max_length=2)),
                ('original_grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('resit_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resit_grade', models.CharField(blank=True, max_length=2)),
                ('resit_grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('resit_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fee_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('missed', 'Missed')], default='registered', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_venue', models.CharField(blank=True, max_length=200)),
                ('attendance', models.BooleanField(default=False)),
                ('marking_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resit_exams_approved', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resit_exams_marked', to=settings.AUTH_USER_MODEL)),
                ('original_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_exams', to='portal.semesterresults')),
                ('original_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_resit_exams', to='portal.semester')),
                ('resit_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_exams', to='portal.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_exams', to='portal.student')),
            ],
            options={
                'db_table': 'resit_exams',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='SemesterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year_of_study', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('to_year_of_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('from_semester_number', models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3')], max_length=1, null=True)),
                ('to_semester_number', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3')], max_length=1)),
                ('failed_units_count', models.IntegerField(default=0)),
                ('is_eligible', models.BooleanField(default=False)),
                ('eligibility_checked_at', models.DateTimeField(blank=True, null=True)),
                ('eligibility_remarks', models.TextField(blank=True)),
                ('fee_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_financially_cleared', models.BooleanField(default=False)),
                ('financial_clearance_date', models.DateTimeField(blank=True, null=True)),
                ('previous_semester_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_credits_earned', models.IntegerField(default=0)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('from_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_from', to='portal.academicyear')),
                ('from_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_from', to='portal.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_reports', to='portal.student')),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_to', to='portal.academicyear')),
                ('to_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_to', to='portal.semester')),
            ],
            options={
                'db_table': 'semester_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='UnitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('normal', 'Normal Enrollment'), ('resit', 'Resit/Supplementary'), ('retake', 'Retake')], default='normal', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_approved', to=settings.AUTH_USER_MODEL)),
                ('programme_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.programmeunit')),
                ('resit_exam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment', to='portal.resitexam')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.semester')),
                ('semester_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_enrollments', to='portal.semesterreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_enrollments', to='portal.student')),
            ],
            options={
                'db_table': 'unit_enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='resitexam',
            index=models.Index(fields=['student', 'status'], name='resit_exams_student_865c64_idx'),
        ),
        migrations.AddIndex(
            model_name='resitexam',
            index=models.Index(fields=['resit_semester', 'status'], name='resit_exams_resit_s_50bf6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resitexam',
            unique_together={('student', 'original_result', 'resit_semester')},
        ),
        migrations.AddIndex(
            model_name='semesterreport',
            index=models.Index(fields=['student', 'status'], name='semester_re_student_cad2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterreport',
            index=models.Index(fields=['to_semester', 'status'], name='semester_re_to_seme_8ff477_idx'),
        ),
        migrations.AddIndex(
            model_name='unitenrollment',
            index=models.Index(fields=['student', 'status'], name='unit_enroll_student_7c9919_idx'),
        ),
        migrations.AddIndex(
            model_name='unitenrollment',
            index=models.Index(fields=['semester', 'status'], name='unit_enroll_semeste_b2cf53_idx'),
        ),
        migrations.AddIndex(
            model_name='unitenrollment',
            index=models.Index(fields=['semester_report'], name='unit_enroll_semeste_42a1d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitenrollment',
            unique_together={('student', 'programme_unit', 'semester')},
        ),
    ]
