# Generated by Django 5.2.8 on 2025-12-29 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_enrollmentperiod_resitexam_semesterreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Week number in the semester (1-15)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('material_type', models.CharField(choices=[('notes', 'Lecture Notes'), ('slides', 'Presentation Slides'), ('assignment', 'Assignment'), ('tutorial', 'Tutorial'), ('reference', 'Reference Material'), ('video', 'Video Link'), ('other', 'Other')], default='notes', max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('word', 'Word Document'), ('image', 'Image'), ('link', 'External Link')], default='pdf', max_length=10)),
                ('topic', models.CharField(help_text='Topic/Title of the material', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Brief description or instructions')),
                ('file', models.FileField(blank=True, help_text='Upload PDF, Word document, or Image', null=True, upload_to='teaching_materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('external_link', models.URLField(blank=True, help_text='YouTube link or other external resource')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, help_text='Make visible to students')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_materials', to='portal.unitallocation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_materials',
                'ordering': ['unit_allocation', 'week_number', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_downloads', to='portal.student')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='portal.teachingmaterial')),
            ],
            options={
                'db_table': 'material_downloads',
                'ordering': ['-download_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portal.materialcomment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_comments', to='portal.student')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portal.teachingmaterial')),
            ],
            options={
                'db_table': 'material_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teachingmaterial',
            index=models.Index(fields=['unit_allocation', 'week_number'], name='teaching_ma_unit_al_2bddc1_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingmaterial',
            index=models.Index(fields=['is_published', 'publish_date'], name='teaching_ma_is_publ_d39648_idx'),
        ),
        migrations.AddIndex(
            model_name='materialdownload',
            index=models.Index(fields=['material', 'student'], name='material_do_materia_294ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='materialdownload',
            index=models.Index(fields=['download_date'], name='material_do_downloa_666613_idx'),
        ),
    ]
