# Generated by Django 5.2.8 on 2025-12-30 09:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_teachingmaterial_materialdownload_materialcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Payment Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_reservations', to='portal.hostelapplication')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='portal.hostelbed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_reservations', to='portal.student')),
            ],
            options={
                'db_table': 'bed_reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostel_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.hostel')),
            ],
            options={
                'db_table': 'hostel_images',
                'ordering': ['display_order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='HostelMaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('furniture', 'Furniture'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance_requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='portal.hostelallocation')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='portal.student')),
            ],
            options={
                'db_table': 'hostel_maintenance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('facilities_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('security_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('management_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('title', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portal.hostelallocation')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portal.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_reviews', to='portal.student')),
            ],
            options={
                'db_table': 'hostel_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.hostelroom')),
            ],
            options={
                'db_table': 'hostel_room_images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_desc', models.CharField(max_length=200)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='portal.bedreservation')),
                ('hostel_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='portal.hostelapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to='portal.student')),
            ],
            options={
                'db_table': 'mpesa_payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('sms_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('allocation_notice', 'Allocation Notice'), ('reminder', 'Reminder')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to='portal.hostelallocation')),
                ('mpesa_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to='portal.mpesapayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='portal.student')),
            ],
            options={
                'db_table': 'sms_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bedreservation',
            index=models.Index(fields=['student', 'status'], name='bed_reserva_student_109483_idx'),
        ),
        migrations.AddIndex(
            model_name='bedreservation',
            index=models.Index(fields=['bed', 'status'], name='bed_reserva_bed_id_120247_idx'),
        ),
        migrations.AddIndex(
            model_name='bedreservation',
            index=models.Index(fields=['expires_at', 'status'], name='bed_reserva_expires_cdf846_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelmaintenancerequest',
            index=models.Index(fields=['student', 'status'], name='hostel_main_student_afb697_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelmaintenancerequest',
            index=models.Index(fields=['status', 'priority'], name='hostel_main_status_5d65ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelreview',
            unique_together={('student', 'allocation')},
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['student', 'status'], name='mpesa_payme_student_35a7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_payme_checkou_d8fc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['mpesa_receipt_number'], name='mpesa_payme_mpesa_r_7a91e8_idx'),
        ),
    ]
