# Generated by Django 5.2.8 on 2026-01-08 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_quickaction_aianalytics_aiknowledgebase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_primary', models.CharField(max_length=15)),
                ('phone_secondary', models.CharField(blank=True, max_length=15)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('office_hours', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'db_table': 'contact_info',
                'ordering': ['display_order', 'department'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('finance', 'Finance'), ('hostel', 'Hostel'), ('library', 'Library'), ('technical', 'Technical'), ('general', 'General')], max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('is_helpful_count', models.IntegerField(default=0)),
                ('is_not_helpful_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['category', 'display_order', '-views_count'],
            },
        ),
        migrations.CreateModel(
            name='SystemGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guide_type', models.CharField(choices=[('getting_started', 'Getting Started'), ('academic', 'Academic'), ('finance', 'Finance'), ('hostel', 'Hostel'), ('library', 'Library'), ('profile', 'Profile Management'), ('troubleshooting', 'Troubleshooting')], max_length=20)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video link')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='system_guides/')),
                ('display_order', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_guides',
                'ordering': ['guide_type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('academic', 'Academic Issue'), ('finance', 'Finance/Fees'), ('hostel', 'Hostel/Accommodation'), ('library', 'Library Services'), ('technical', 'Technical/Portal'), ('id_card', 'Student ID Card'), ('results', 'Results/Grades'), ('registration', 'Registration'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_tickets/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_response', 'Waiting for Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='portal.student')),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_replies/')),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portal.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ticket Replies',
                'db_table': 'ticket_replies',
                'ordering': ['created_at'],
            },
        ),
    ]
