# Generated by Django 5.2.8 on 2026-01-25 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alumnirelation_annualplan_budgetallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('academic', 'Academic Concern'), ('attendance', 'Attendance Issue'), ('performance', 'Performance Discussion'), ('personal', 'Personal Issue'), ('career', 'Career Guidance'), ('general', 'General Note')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('action_required', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_notes_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_notes', to='portal.student')),
            ],
            options={
                'db_table': 'advising_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSpecialNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_type', models.CharField(choices=[('physical', 'Physical Disability'), ('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('learning', 'Learning Disability'), ('medical', 'Medical Condition'), ('mental', 'Mental Health'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=10)),
                ('description', models.TextField()),
                ('accommodations_required', models.TextField(help_text='Special accommodations needed')),
                ('support_provided', models.TextField(blank=True)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='special_needs/')),
                ('reported_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_needs_reported', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_needs', to='portal.student')),
            ],
            options={
                'db_table': 'student_special_needs',
                'ordering': ['-created_at'],
            },
        ),
    ]
