# Generated by Django 6.0.1 on 2026-02-04 04:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_advisingnote_studentspecialneed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('member_type', models.CharField(choices=[('chairman', 'Chairman'), ('vice_chairman', 'Vice Chairman'), ('member', 'Council Member'), ('secretary', 'Secretary'), ('ex_officio', 'Ex-Officio Member')], max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('appointment_date', models.DateField()),
                ('term_end_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='council/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'university_council',
                'ordering': ['member_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CapitalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('funding_source', models.CharField(max_length=200)),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('expected_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('design', 'Design'), ('tendering', 'Tendering'), ('construction', 'Under Construction'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capital_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternationalRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('qs', 'QS World University Rankings'), ('times', 'Times Higher Education'), ('arwu', 'Academic Ranking of World Universities'), ('usnews', 'US News Rankings'), ('webometrics', 'Webometrics')], max_length=20)),
                ('year', models.IntegerField()),
                ('overall_rank', models.IntegerField(blank=True, null=True)),
                ('national_rank', models.IntegerField(blank=True, null=True)),
                ('regional_rank', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category_scores', models.JSONField(default=dict)),
                ('analysis', models.TextField(blank=True)),
                ('report_document', models.FileField(blank=True, null=True, upload_to='rankings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'international_rankings',
                'ordering': ['-year', 'ranking_type'],
                'unique_together': {('ranking_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ManagementBoardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_number', models.CharField(max_length=50, unique=True)),
                ('meeting_date', models.DateField()),
                ('agenda', models.TextField()),
                ('decisions', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('minutes_document', models.FileField(blank=True, null=True, upload_to='management_board/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.academicyear')),
            ],
            options={
                'db_table': 'management_board_meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_number', models.CharField(max_length=50, unique=True)),
                ('risk_category', models.CharField(choices=[('strategic', 'Strategic Risk'), ('operational', 'Operational Risk'), ('financial', 'Financial Risk'), ('compliance', 'Compliance Risk'), ('reputational', 'Reputational Risk'), ('technology', 'Technology Risk')], max_length=20)),
                ('risk_title', models.CharField(max_length=300)),
                ('risk_description', models.TextField()),
                ('likelihood', models.CharField(choices=[('rare', 'Rare'), ('unlikely', 'Unlikely'), ('possible', 'Possible'), ('likely', 'Likely'), ('almost_certain', 'Almost Certain')], max_length=20)),
                ('impact', models.CharField(choices=[('insignificant', 'Insignificant'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('catastrophic', 'Catastrophic')], max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('mitigation_strategy', models.TextField()),
                ('review_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_register',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='SenateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(max_length=50, unique=True)),
                ('session_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('agenda', models.TextField()),
                ('minutes', models.TextField(blank=True)),
                ('decisions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('minutes_document', models.FileField(blank=True, null=True, upload_to='senate/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senate_sessions', to='portal.academicyear')),
                ('attendees', models.ManyToManyField(blank=True, related_name='senate_attended', to=settings.AUTH_USER_MODEL)),
                ('chaired_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'senate_sessions',
                'ordering': ['-session_date'],
            },
        ),
    ]
